config/routes.rb
ContactoVeWebApp::Application.routes.draw do
  resources :surveys, :only => [:index, :edit, :update]

  resources :companies, :only => [:index, :show, :edit, :update] do
    resources :meeting_requests, only: [ :new, :create ]
  end

  resources :meetings, only: :index
  resources :meeting_requests, only: :index do
    member do
      get :accept
      get :reject
    end
  end

  devise_for :users

  namespace :admin do
    resources :users do
      collection do
        get :admins
        get :sponsors
        get :anchors
      end
    end

    resources :meetings
    resources :meeting_requests do
      member do
        get :notify
      end
    end
    resources :companies do
      collection do
        get :sponsors
        get :anchors
      end

      member do
        get :schedule
        get :send_schedule
      end
    end

    resources :surveys, :only => [:index, :edit, :update]

    get 'survey_users',     to: 'surveys#users'
    get 'survey_companies', to: 'surveys#companies'
    get 'survey_user/:id',  to: 'surveys#user', as: 'survey_user'

    authenticate :user, lambda { |u| u.admin? } do
      mount Resque::Server, :at => "/resque"
      mount MailPreview,    :at => "/mail_view"
    end
  end

  root 'dashboard#show'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions

  accepts_nested_attributes_for :questions
end

app/controllers/admin/surveys_controller.rb
module Admin
  class SurveysController < AdministrationController
    before_action :set_survey, only: [:show, :edit, :update, :destroy]

    # GET /surveys
    # GET /surveys.json
    def index
      @survey  = Survey.first
      @count = 1
    end

    def companies
      @survey  = Survey.first
      @users = User.includes(:answers).where("answers is not null").references(:answers)
    end

    def users
      @users = User.includes(:answers).where("answers is not null").references(:answers)
    end

    def user
      @survey  = Survey.first
      @user = User.find(params[:id])
    end

    # GET /surveys/new
    def new
      @survey = Survey.new
    end

    # GET /surveys/1/edit
    def edit
    end

    # POST /surveys
    # POST /surveys.json
    def create
      @survey = Survey.new(survey_params)

      respond_to do |format|
        if @survey.save
          format.html { redirect_to surveys_path, notice: 'Survey was successfully created.' }
          format.json { render action: 'show', status: :created, location: @survey }
        else
          format.html { render action: 'new' }
          format.json { render json: @survey.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /surveys/1
    # PATCH/PUT /surveys/1.json
    def update
      respond_to do |format|
        if @survey.update(survey_params)
          format.html { redirect_to surveys_path, notice: 'Survey was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @survey.errors, status: :unprocessable_entity }
        end
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_survey
        @survey = Survey.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def survey_params
        params.require(:survey).permit(:name)
        params.require(:survey).permit(:name,
          :questions_attributes => [:id, :name,
            :answers_attributes => [:id, :user_id, :question_id, :possible_answer_id, :text]
          ])
      end
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @company = current_user.company
    @survey  = Survey.first
    @count = 1;
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to surveys_path, notice: 'La encuesta se ha enviado exitosamente.' }
        format.json { render action: 'show', status: :created, location: @survey }
      else
        format.html { render action: 'new' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to surveys_path, notice: 'La encuesta se ha enviado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name)
      params.require(:survey).permit(:name,
        :questions_attributes => [:id, :name,
          :answers_attributes => [:id, :user_id, :question_id, :possible_answer_id, :text]
        ])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/admin/surveys/companies.html.erb
<%- content_for :header do -%>
<%= render partial: 'admin/menu' %>
<%- end -%>

<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<ul class="nav nav-pills">
  <li <%= 'class="active"'.html_safe if action_name == 'index' %>>
    <%= link_to t('.all'), admin_surveys_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'companies' %>>
    <%= link_to t('.by_companies'), admin_survey_companies_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'users' %>>
    <%= link_to t('.users'), admin_survey_users_path %>
  </li>
</ul>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="width: 30%"><%=t '.questions' %></th>
      <th><%=t '.answers' %></th>
    </tr>
  </thead>
  <tbody>
    <% @survey.questions.order('id asc').each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td>
          <% unless question.answers.blank? %>
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Empresa</th>
                  <th><%=t '.answers' %></th>
                  <th>Texto</th>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <% user.answers.by_question(question).each do |answer|%>
                    <% unless answer.blank? %>
                      <tr>
                        <td><%= "#{user.full_name} | #{user.company.name}" %></td>
                        <td>
                          <% unless answer.possible_answer.blank? %>
                            <%= answer.possible_answer.text %>
                          <% end %>
                        </td>
                        <td><%= answer.text %></td>
                      </tr>
                    <% end %>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/surveys/index.html.erb
<%- content_for :header do -%>
<%= render partial: 'admin/menu' %>
<%- end -%>

<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<ul class="nav nav-pills">
  <li <%= 'class="active"'.html_safe if action_name == 'index' %>>
    <%= link_to t('.all'), admin_surveys_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'companies' %>>
    <%= link_to t('.by_companies'), admin_survey_companies_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'users' %>>
    <%= link_to t('.users'), admin_survey_users_path %>
  </li>
</ul>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th style="width: 30%"><%=t '.questions' %></th>
      <th><%=t '.answers' %></th>
    </tr>
  </thead>
  <tbody>
    <% @survey.questions.order('id asc').each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td>
          <% unless question.answers.blank? %>
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th><%=t '.answers' %></th>
                  <th><%=t '.total' %></th>
                  <th><%=t '.percentage' %></th>
                  <th><%=t '.text' %></th>
                </tr>
              </thead>
              <tbody>
                <% question.possible_answers.each do |pa|%>
                  <tr>
                    <% if pa.option || !pa.answers.blank? %>
                      <td><%= pa.text %></td>
                      <td><%= pa.answers.count %></td>
                      <td><%= pa.answers.count == 0 ? 0 : 
                  ((pa.answers.count.to_f * 100.0) / User.all.count.to_f) %>%</td>
                      <td>
                        <% unless pa.answers.blank? %>
                          <ul>
                          <% pa.answers.each do |a| %>
                            <% unless a.text.blank? %>
                              <li><%= a.text %></li>
                            <% end %>
                          <% end %>
                          </ul>
                        <% end %>
                      </td>
                    <% else %>
                      <td colspan="4"><%= pa.text %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/surveys/user.html.erb
<%- content_for :header do -%>
<%= render partial: 'admin/menu' %>
<%- end -%>

<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<ul class="nav nav-pills">
  <li <%= 'class="active"'.html_safe if action_name == 'index' %>>
    <%= link_to t('.all'), admin_surveys_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'companies' %>>
    <%= link_to t('.by_companies'), admin_survey_companies_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'users' %>>
    <%= link_to t('.users'), admin_survey_users_path %>
  </li>
</ul>

<div class="row">
  <div class="company survey">
  <%= form_for(@survey) do |f| %>
    <% @survey.questions.order('id asc').each_with_index do |question, index| %>
      <% if index == 0 %>
        <% @count = 1 %>
        <h3 class="section-title info">
          BLOQUE 1: Sobre el Encuentro:
        </h3>
      <% elsif index == 2 %>
        <% @count = 1 %>
        <h3 class="section-title services">
          BLOQUE 2: Sobre el contacto:
        </h3>
      <% elsif index == 4 %>
        <% @count = 1 %>
        <h3 class="section-title needs">
          BLOQUE 3: Sobre la Alianza:
        </h3>
      <% elsif index == 15 %>
        <% @count = 1 %>
        <h3 class="section-title offers">
          BLOQUE 4: Sobre la red.
        </h3>
      <% end %>

      <% unless question.possible_answers.empty? %>
        <div id="summary-block" class="survey-block">
          <p><%= "#{@count}. #{question.text}" %></p>
          <%= f.fields_for :questions, question do |q| %>
            <% @count = @count + 1 %>
            <%= q.fields_for :answers, question.answers.find_or_initialize_by(user: @user) do |a| %>
              <% question.possible_answers.order('id asc').each do |pa| %>
                <%= a.hidden_field :user_id, value: @user.id %>
                <%= a.hidden_field :question_id, value: question.id %>
                <% unless pa.option %>
                  <p><%= pa.text %></p>
                <% else %>
                  <label class="radio <%= question.possible_answers.count == 8 ? 'inline' : '' %>">
                    <%= a.radio_button :possible_answer_id, pa.id, class: "radio inline" %>
                    <%= pa.text %>
                  </label>
                <% end %>
                <% if pa.explain %>
                  <%= a.text_area :text, :rows => 2, :class => "span9" %>
                  <% if !pa.option %>
                    <%= a.hidden_field :possible_answer_id, value: pa.id %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/admin/surveys/users.html.erb
<%- content_for :header do -%>
<%= render partial: 'admin/menu' %>
<%- end -%>

<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<ul class="nav nav-pills">
  <li <%= 'class="active"'.html_safe if action_name == 'index' %>>
    <%= link_to t('.all'), admin_surveys_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'companies' %>>
    <%= link_to t('.by_companies'), admin_survey_companies_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'users' %>>
    <%= link_to t('.users'), admin_survey_users_path %>
  </li>
</ul>

<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:company_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.full_name %>

          <% if user.mobile_phone %>
            <small>(<%= user.mobile_phone %>)</small>
          <% end %>

          <div class="email"><%= link_to user.email, admin_user_path(user) %></div>

          <% if user.admin %>
            <span class="badge badge-inverse">admin</span>
          <% end %>
          <% if user.company && user.company.sponsor %>
            <span class="badge badge-warning">sponsor</span>
          <% end %>
          <% if user.company && user.company.anchor %>
            <span class="badge badge-info">anchor</span>
          <% end %>
        </td>
        <td><%= user.company %></td>
        <td>
          <%= link_to t('.survey'), admin_survey_user_path(user), :class => 'btn btn-mini' %>
        </td>
      </tr>
      <tr>
      </tr>
    <% end %>
  </tbody>
</table>