config/routes.rb
ContactoVeWebApp::Application.routes.draw do
  resources :surveys, :only => [:index, :edit, :update]

  resources :companies, :only => [:index, :show, :edit, :update] do
    resources :meeting_requests, only: [ :new, :create ]
  end

  resources :meetings, only: :index
  resources :meeting_requests, only: :index do
    member do
      get :accept
      get :reject
    end
  end

  devise_for :users

  namespace :admin do
    resources :users do
      collection do
        get :admins
        get :sponsors
        get :anchors
      end
    end

    resources :meetings
    resources :meeting_requests do
      member do
        get :notify
      end
    end
    resources :companies do
      collection do
        get :sponsors
        get :anchors
      end

      member do
        get :schedule
        get :send_schedule
      end
    end

    resources :surveys, :only => [:index, :edit, :update]

    get 'survey_users',     to: 'surveys#users'
    get 'survey_companies', to: 'surveys#companies'
    get 'survey_user/:id',  to: 'surveys#user', as: 'survey_user'

    authenticate :user, lambda { |u| u.admin? } do
      mount Resque::Server, :at => "/resque"
      mount MailPreview,    :at => "/mail_view"
    end
  end

  root 'dashboard#show'
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :sector
  belongs_to :contact_person, class_name: User.to_s
  
  mount_uploader :logo, ImageUploader

  has_many :incoming_meeting_requests, class_name: MeetingRequest.to_s, foreign_key: :requestee_company_id
  has_many :outgoing_meeting_requests, class_name: MeetingRequest.to_s, foreign_key: :requester_company_id

  scope :sponsors, -> { where(sponsor: true) }
  scope :anchors,  -> { where(anchor: true) }
  scope :search,   ->(name) { t = Company.arel_table; where t[:name].matches("%#{name}%") }

  def has_meeting_with(company)
    t = Meeting.arel_table
    requested_by_us   = t.grouping(t[:requester_company_id].eq(id).and(t[:company_id].eq(company.id)))
    requested_by_them = t.grouping(t[:requester_company_id].eq(company.id).and(t[:company_id].eq(id)))

    Meeting.where(requested_by_us.or(requested_by_them)).count > 0
  end

  def meetings
    t = Meeting.arel_table
    Meeting.where(t[:requester_company_id].eq(id).or(t[:company_id].eq(id)))
  end

  def confirmed_meetings
    meetings.first_block | meetings.second_block | meetings.third_block
  end

  def all_available_meeting_spots
    available_meeting_spots(:first_block) + available_meeting_spots(:second_block) + available_meeting_spots(:third_block)
  end

  def available_meeting_spots(block_number)
    block_spots = Meeting.spots(block_number)

    if sponsor
      block_spots *= 2 # duplicate available spots
      block_spots.sort! { |x,y| x[:begin_at] <=> y[:begin_at] }
    end

    booked_spots = meetings.send(block_number).pluck(:begin_at)
    block_spots.reject do |spot|
      index = booked_spots.index spot[:begin_at]

      booked_spots.delete_at index if index
      index
    end
  end

  def max_meetings_per_spot
    sponsor? ? 2 : 1
  end

  def max_meetings
    @max_meetings ||= Meeting.all_spots.count * max_meetings_per_spot
  end

  def max_incoming_requests
    if self[:incoming_request_limit] < 0
      max_meetings / 2
    else
      self[:incoming_request_limit]
    end
  end

  def max_outgoing_requests
    if self[:outgoing_request_limit] < 0
      max_meetings / 2
    else
      self[:outgoing_request_limit]
    end
  end

  def max_time_limit
    time_limit.blank? ? Time.parse("2013-07-01 15:01:00 -0430") : time_limit
  end

  def to_s
    name
  end
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < AdministrationController
    before_action :set_company, only: [:show, :edit, :update, :destroy, :schedule, :send_schedule]

    # GET /companies
    # GET /companies.json
    def index
      @companies ||= Company.all
      @companies = @companies.search params[:search] if params[:search] && !params[:search].empty?

      @companies = @companies.page(params[:page])

      render 'index'
    end

    def sponsors
      @companies = Company.sponsors
      index
    end

    def anchors
      @companies = Company.anchors
      index
    end

    # GET /companies/1
    # GET /companies/1.json
    def show
    end

    def schedule
      respond_to do |format|
        format.pdf do
          pdf = ScheduleDocument.new(@company)
          send_data pdf.render, filename: 'contacto-ve-agenda.pdf',
                                type: 'application/pdf',
                                disposition: 'inline'
        end
      end
    end

    def send_schedule
      MeetingRequestMailer.pdf_schedule(@company.id).deliver
    end

    # GET /companies/new
    def new
      @company = Company.new
    end

    # GET /companies/1/edit
    def edit
    end

    # POST /companies
    # POST /companies.json
    def create
      @company = Company.new(company_params)

      respond_to do |format|
        if @company.save
          format.html { redirect_to [:admin, @company], notice: 'Admin company was successfully created.' }
        else
          format.html { render action: 'new' }
        end
      end
    end

    # PATCH/PUT /companies/1
    # PATCH/PUT /companies/1.json
    def update
      respond_to do |format|
        if @company.update(company_params)
          format.html { redirect_to [:admin, @company], notice: 'Admin company was successfully updated.' }
        else
          format.html { render action: 'edit' }
        end
      end
    end

    # DELETE /companies/1
    # DELETE /companies/1.json
    def destroy
      @company.destroy
      respond_to do |format|
        format.html { redirect_to admin_companies_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_company
        @company = Company.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def company_params
        params.require(:company).permit(:external_id, :logo, :name, :sector_id, :contact_person_id, :website, :twitter,
          :phone_number, :summary, :services, :needs, :offers, :sponsor, :anchor, :incoming_request_limit, :outgoing_request_limit, :time_limit) if params[:query].nil?
      end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update]

  # GET /companies
  def index
    @sectors = Sector.all
    @company = current_user.company
    if (params[:sector_id])
      @companies = Company.where(:sector_id => params[:sector_id]).order('name asc').page(params[:page]).per(6) 
      @sector = Sector.find(params[:sector_id])     
    elsif (params[:company_name])
      @companies = Company.where("name ilike '%#{params[:company_name]}%'").order('name asc').page(params[:page]).per(6)
    else
      @companies = Company.all.page(params[:page]).order('name asc').per(6)
    end
  end

  # GET /companies/1
  def show
  end

  # GET /companies/1/edit
  def edit
    @user = @company.contact_person
    respond_to do |format|
      format.js {}
    end
  end

  # PATCH/PUT /companies/1
  def update
    respond_to do |format|
      if @company.update(company_params)
        @user = @company.contact_person
        @user.update(user_params)
        format.html { redirect_to @company, notice: 'Sus datos se han actualizado exitosamente.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :summary, :services, :needs, :offers, :sector_id, :website, :twitter, :logo)
    end
    
    def user_params
      if !params[:user].nil?
        params[:user].permit(:first_name, :last_name, :phone_number, :email, :mobile_phone)
      end
    end
end

app/views/admin/companies/_form.html.erb
<%= form_for [:admin, @company], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <div class="control-group">
      <%= f.label :external_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :external_id, :class => 'text_field' %>
      </div>
    </div>
    <%= f.label :logo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :logo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sector_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :sector_id, Sector.all, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contact_person_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :contact_person_id, User.all, :id, :full_name, include_blank: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :twitter, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitter, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :summary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :summary, :rows => 5, :class => 'span4' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :services, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :services, :rows => 5, :class => 'span4' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :needs, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :needs, :rows => 5, :class => 'span4' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :offers, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :offers, :rows => 5, :class => 'span4' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sponsor, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :sponsor, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :anchor, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :anchor, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :incoming_request_limit, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :incoming_request_limit, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :outgoing_request_limit, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :outgoing_request_limit, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time_limit, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_field :time_limit %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_companies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/companies/index.html.erb
<%- content_for :header do -%>
<%= render partial: 'admin/menu' %>
<%- end -%>

<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<ul class="nav nav-pills">
  <li <%= 'class="active"'.html_safe if action_name == 'index' %>>
    <%= link_to t('.all'), admin_companies_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'sponsors' %>>
    <%= link_to t('.sponsors'), sponsors_admin_companies_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'anchors' %>>
    <%= link_to t('.anchors'), anchors_admin_companies_path %>
  </li>
</ul>

<%= paginate @companies %>

<form class="form-search">
  <input type="text" name="search" class="input-medium search-query" value="<%= params[:search] %>"/>
  <button type="submit" class="btn"><%=t '.search' %></button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:external_id) %></th>
      <th><%= model_class.human_attribute_name(:logo) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:contact_information) %></th>
      <th><%=t '.incoming' %></th>
      <th><%=t '.outgoing' %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.external_id %></td>
        <td>
          <%= link_to admin_company_path(company) do %>
            <%= image_tag company.logo, alt: company.name, width: 50, height: 50 %>
          <% end %>
        </td>
        <td>
          <%= link_to company.name, admin_company_path(company) %>

          <% if company.sponsor %>
            <span class="badge badge-warning">sponsor</span>
          <% end %>
          <% if company.anchor %>
            <span class="badge badge-info">anchor</span>
          <% end %>

          <div class="sector"><%= company.sector %></div>
        </td>
        <td>
          <%= company.contact_person %>

          <% if company.twitter %>
            <div class="twitter"><%= link_to company.twitter, "http://twitter.com/#{company.twitter.sub '@', ''}" %></div>
          <% end %>

          <% if company.website %>
            <div class="website"><%= link_to company.website %></div>
          <% end %>

          <div class="phone-number"><%= company.phone_number %></div>
        </td>
        <td>
          <%= company.incoming_meeting_requests.scheduled.count %> /
          <%= company.incoming_meeting_requests.count %>
          (<%= company.max_incoming_requests %>)
        </td>
        <td>
          <%= company.outgoing_meeting_requests.scheduled.count %> /
          <%= company.outgoing_meeting_requests.count %>
          (<%= company.max_outgoing_requests %>)
        </td>
        <td><%= company.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_company_path(company), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_company_path(company),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @companies %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_company_path,
            :class => 'btn btn-primary' %>

app/views/admin/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="row">
  <div class="span2">
    <%= image_tag @company.logo, alt: @company.name %>
  </div>
  <div class="span10">
    <h2>
      <%= @company.name %>

      <small><%= @company.sector %></small>

      <% if @company.sponsor %>
        <span class="badge badge-warning">sponsor</span>
      <% end %>
      <% if @company.anchor %>
        <span class="badge badge-info">anchor</span>
      <% end %>

      <%= link_to '&nbsp;'.html_safe, schedule_admin_company_path(format: :pdf), class: 'icon-download-alt' %>
      <%= link_to '&nbsp;'.html_safe, send_schedule_admin_company_path, class: 'icon-share' %>
    </h2>

    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:contact_person_id) %>:</strong></dt>
      <dd><%= link_to @company.contact_person, [:admin, @company.contact_person] if @company.contact_person %>
        (<%= mail_to @company.contact_person.email unless @company.contact_person.blank? %>)</dd>
      <dt><strong><%= model_class.human_attribute_name(:external_id) %>:</strong></dt>
      <dd><%= @company.external_id %></dd>
      <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
      <dd><%= @company.website %></dd>
      <dt><strong><%= model_class.human_attribute_name(:twitter) %>:</strong></dt>
      <dd><%= @company.twitter %></dd>
      <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
      <dd><%= @company.phone_number %></dd>
    </dl>

    <dl class="dl-horizontal alert alert-info">
      <dt><strong><%= model_class.human_attribute_name(:max_incoming_requests) %>:</strong></dt>
      <dd><%= @company.max_incoming_requests %></dd>
      <dt><strong><%= model_class.human_attribute_name(:max_outgoing_requests) %>:</strong></dt>
      <dd><%= @company.max_outgoing_requests %></dd>
      <dt><strong><%= model_class.human_attribute_name(:max_time_limit) %>:</strong></dt>
      <dd><%= @company.max_time_limit %></dd>
    </dl>

    <dl>
      <% [:summary, :services, :needs, :offers].each do |attribute| %>
        <% if @company.send(attribute) %>
          <dt><strong><%= model_class.human_attribute_name(attribute) %>:</strong></dt>
          <dd><%= @company.send(attribute) %></dd>
        <% end %>
      <% end %>
    </dl>

    <h3><%=t '.incoming_meeting_requests' %></h3>
    <ul>
    <% @company.incoming_meeting_requests.each do |m| %>
      <li>
        <strong><%= link_to m.other_company(@company).name.upcase, admin_company_path(m.other_company(@company)) %></strong>
        <%= status_label m.status %>
        <%= link_to notify_admin_meeting_request_path(m), title: t('.notification_resend') do %>
          <i class="icon-repeat"></i>
        <% end %>
        <%= link_to admin_meeting_request_path(m),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
          <i class="icon-remove"></i>
        <% end %>
      </li>
    <% end %>
    </ul>

    <h3><%=t '.outgoing_meeting_requests' %></h3>
    <ul>
    <% @company.outgoing_meeting_requests.each do |m| %>
      <li>
        <strong><%= link_to m.other_company(@company).name.upcase, admin_company_path(m.other_company(@company)) %></strong>
        <%= status_label m.status %>
        <%= link_to notify_admin_meeting_request_path(m), title: t('.notification_resend') do %>
          <i class="icon-repeat"></i>
        <% end %>
        <%= link_to admin_meeting_request_path(m),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
          <i class="icon-remove"></i>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_companies_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_company_path(@company), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_company_path(@company),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>