config/routes.rb
ContactoVeWebApp::Application.routes.draw do
  resources :surveys, :only => [:index, :edit, :update]

  resources :companies, :only => [:index, :show, :edit, :update] do
    resources :meeting_requests, only: [ :new, :create ]
  end

  resources :meetings, only: :index
  resources :meeting_requests, only: :index do
    member do
      get :accept
      get :reject
    end
  end

  devise_for :users

  namespace :admin do
    resources :users do
      collection do
        get :admins
        get :sponsors
        get :anchors
      end
    end

    resources :meetings
    resources :meeting_requests do
      member do
        get :notify
      end
    end
    resources :companies do
      collection do
        get :sponsors
        get :anchors
      end

      member do
        get :schedule
        get :send_schedule
      end
    end

    resources :surveys, :only => [:index, :edit, :update]

    get 'survey_users',     to: 'surveys#users'
    get 'survey_companies', to: 'surveys#companies'
    get 'survey_user/:id',  to: 'surveys#user', as: 'survey_user'

    authenticate :user, lambda { |u| u.admin? } do
      mount Resque::Server, :at => "/resque"
      mount MailPreview,    :at => "/mail_view"
    end
  end

  root 'dashboard#show'
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :sector
  belongs_to :contact_person, class_name: User.to_s
  
  mount_uploader :logo, ImageUploader

  has_many :incoming_meeting_requests, class_name: MeetingRequest.to_s, foreign_key: :requestee_company_id
  has_many :outgoing_meeting_requests, class_name: MeetingRequest.to_s, foreign_key: :requester_company_id

  scope :sponsors, -> { where(sponsor: true) }
  scope :anchors,  -> { where(anchor: true) }
  scope :search,   ->(name) { t = Company.arel_table; where t[:name].matches("%#{name}%") }

  def has_meeting_with(company)
    t = Meeting.arel_table
    requested_by_us   = t.grouping(t[:requester_company_id].eq(id).and(t[:company_id].eq(company.id)))
    requested_by_them = t.grouping(t[:requester_company_id].eq(company.id).and(t[:company_id].eq(id)))

    Meeting.where(requested_by_us.or(requested_by_them)).count > 0
  end

  def meetings
    t = Meeting.arel_table
    Meeting.where(t[:requester_company_id].eq(id).or(t[:company_id].eq(id)))
  end

  def confirmed_meetings
    meetings.first_block | meetings.second_block | meetings.third_block
  end

  def all_available_meeting_spots
    available_meeting_spots(:first_block) + available_meeting_spots(:second_block) + available_meeting_spots(:third_block)
  end

  def available_meeting_spots(block_number)
    block_spots = Meeting.spots(block_number)

    if sponsor
      block_spots *= 2 # duplicate available spots
      block_spots.sort! { |x,y| x[:begin_at] <=> y[:begin_at] }
    end

    booked_spots = meetings.send(block_number).pluck(:begin_at)
    block_spots.reject do |spot|
      index = booked_spots.index spot[:begin_at]

      booked_spots.delete_at index if index
      index
    end
  end

  def max_meetings_per_spot
    sponsor? ? 2 : 1
  end

  def max_meetings
    @max_meetings ||= Meeting.all_spots.count * max_meetings_per_spot
  end

  def max_incoming_requests
    if self[:incoming_request_limit] < 0
      max_meetings / 2
    else
      self[:incoming_request_limit]
    end
  end

  def max_outgoing_requests
    if self[:outgoing_request_limit] < 0
      max_meetings / 2
    else
      self[:outgoing_request_limit]
    end
  end

  def max_time_limit
    time_limit.blank? ? Time.parse("2013-07-01 15:01:00 -0430") : time_limit
  end

  def to_s
    name
  end
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < AdministrationController
    before_action :set_company, only: [:show, :edit, :update, :destroy, :schedule, :send_schedule]

    # GET /companies
    # GET /companies.json
    def index
      @companies ||= Company.all
      @companies = @companies.search params[:search] if params[:search] && !params[:search].empty?

      @companies = @companies.page(params[:page])

      render 'index'
    end

    def sponsors
      @companies = Company.sponsors
      index
    end

    def anchors
      @companies = Company.anchors
      index
    end

    # GET /companies/1
    # GET /companies/1.json
    def show
    end

    def schedule
      respond_to do |format|
        format.pdf do
          pdf = ScheduleDocument.new(@company)
          send_data pdf.render, filename: 'contacto-ve-agenda.pdf',
                                type: 'application/pdf',
                                disposition: 'inline'
        end
      end
    end

    def send_schedule
      MeetingRequestMailer.pdf_schedule(@company.id).deliver
    end

    # GET /companies/new
    def new
      @company = Company.new
    end

    # GET /companies/1/edit
    def edit
    end

    # POST /companies
    # POST /companies.json
    def create
      @company = Company.new(company_params)

      respond_to do |format|
        if @company.save
          format.html { redirect_to [:admin, @company], notice: 'Admin company was successfully created.' }
        else
          format.html { render action: 'new' }
        end
      end
    end

    # PATCH/PUT /companies/1
    # PATCH/PUT /companies/1.json
    def update
      respond_to do |format|
        if @company.update(company_params)
          format.html { redirect_to [:admin, @company], notice: 'Admin company was successfully updated.' }
        else
          format.html { render action: 'edit' }
        end
      end
    end

    # DELETE /companies/1
    # DELETE /companies/1.json
    def destroy
      @company.destroy
      respond_to do |format|
        format.html { redirect_to admin_companies_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_company
        @company = Company.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def company_params
        params.require(:company).permit(:external_id, :logo, :name, :sector_id, :contact_person_id, :website, :twitter,
          :phone_number, :summary, :services, :needs, :offers, :sponsor, :anchor, :incoming_request_limit, :outgoing_request_limit, :time_limit) if params[:query].nil?
      end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update]

  # GET /companies
  def index
    @sectors = Sector.all
    @company = current_user.company
    if (params[:sector_id])
      @companies = Company.where(:sector_id => params[:sector_id]).order('name asc').page(params[:page]).per(6) 
      @sector = Sector.find(params[:sector_id])     
    elsif (params[:company_name])
      @companies = Company.where("name ilike '%#{params[:company_name]}%'").order('name asc').page(params[:page]).per(6)
    else
      @companies = Company.all.page(params[:page]).order('name asc').per(6)
    end
  end

  # GET /companies/1
  def show
  end

  # GET /companies/1/edit
  def edit
    @user = @company.contact_person
    respond_to do |format|
      format.js {}
    end
  end

  # PATCH/PUT /companies/1
  def update
    respond_to do |format|
      if @company.update(company_params)
        @user = @company.contact_person
        @user.update(user_params)
        format.html { redirect_to @company, notice: 'Sus datos se han actualizado exitosamente.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :summary, :services, :needs, :offers, :sector_id, :website, :twitter, :logo)
    end
    
    def user_params
      if !params[:user].nil?
        params[:user].permit(:first_name, :last_name, :phone_number, :email, :mobile_phone)
      end
    end
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => {:class => "form-horizontal form-edit-company modal", :multipart => true}) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%=f.label :logo, :class => "control-label" %>
    <div class="controls">
      <%=f.file_field :logo %>
    </div>
  </div>
  
  <div class="control-group">
    <%=f.label :name, :class => "control-label" %>
    <div class="controls">
      <%=f.text_field :name %>
    </div>
  </div>
  
  <div class="control-group">
    <%=f.label :sector_id, :class => "control-label" %>
    <div class="controls">
      <%=f.select :sector_id, options_for_select(Sector.all.collect {|s| [ s.name, s.id ]}) %>
    </div>
  </div>
  
  <div class="control-group">
    <%=f.label :website, :class => "control-label" %>
    <div class="controls">
      <%=f.text_field :website %>
    </div>
  </div>
  
  <div class="control-group">
    <%=f.label :twitter, :class => "control-label" %>
    <div class="controls">
      <%=f.text_field :twitter %>
    </div>
  </div>
  
  <%= fields_for @user do |fa| %>
    <div class="control-group">
      <%=fa.label :first_name, :class => "control-label" %>
      <div class="controls">
        <%=fa.text_field :first_name %>
      </div>
    </div>
    
    <div class="control-group"> 
      <%=fa.label :last_name, :class => "control-label" %>
      <div class="controls">
        <%=fa.text_field :last_name %>
      </div>
    </div>
     
    <div class="control-group">
      <%=fa.label :phone_number, :class => "control-label" %>
      <div class="controls">
        <%=fa.text_field :phone_number %>
      </div>
    </div>
    
    <div class="control-group">
      <%=fa.label :email, :class => "control-label" %>
      <div class="controls">
        <%=fa.text_field :email %>
      </div>
    </div>
    
    <div class="control-group">
      <%=fa.label :mobile_phone, :class => "control-label" %>
      <div class="controls">
        <%=fa.text_field :mobile_phone %>
      </div>
    </div>
    
  <% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Actualizar datos"%>
    </div>
  </div>
<% end %>

app/views/companies/_summary.html.erb
<div class="row header-banner">
  
  <div class="user-menu">
    <%= link_to t('.my_profile'), company_path(current_user.company) %> |
    <%= link_to t('.search'), companies_path %> |
   <!-- <%= link_to t('.schedule'), meetings_path %> | -->
    <%= link_to t('.meeting_requests'), meeting_requests_path %> |
    <%= link_to t('.poll'), surveys_path %>
  </div>

  <%= image_tag @company.logo.to_s, :class => "company-logo" %>
  
  <dl class="dl-horizontal">
    <h3><%= !@company.name.blank? ? @company.name.upcase : '&nbsp;'.html_safe  %></h3>
  
    <dt><%= Company.human_attribute_name :sector %></dt>
    <dd><%= !@company.sector.name.blank? ? @company.sector.name : '&nbsp;'.html_safe  %></dd>

    <dt><%= Company.human_attribute_name :contact_person %></dt>
    <dd><%= !@company.contact_person.full_name.blank? ? @company.contact_person.full_name : '&nbsp;'.html_safe  %></dd>
    
    <dt><%= User.human_attribute_name :mobile_phone %></dt>
    <dd><%= !@company.contact_person.mobile_phone.blank? ? @company.contact_person.mobile_phone : '&nbsp;'.html_safe  %></dd>

    <dt><%= User.human_attribute_name :email %></dt>
    <dd><%= !@company.contact_person.email.blank? ? @company.contact_person.email : '&nbsp;'.html_safe  %></dd>
    
    <dt><%= Company.human_attribute_name :website %></dt>
    <dd><%= !@company.website.blank? ? @company.website : '&nbsp;'.html_safe  %></dd>
    
    <dt><%= Company.human_attribute_name :twitter %></dt>
    <dd><%= !@company.twitter.blank? ? @company.twitter : '&nbsp;'.html_safe  %></dd>
    
    <dt><%= User.human_attribute_name :phone_number %></dt>
    <dd><%= !@company.contact_person.phone_number.blank? ? @company.contact_person.phone_number : '&nbsp;'.html_safe  %></dd>
  </dl>
  
  <% if @company == current_user.company %>
      
    <%= link_to t('.edit'), edit_company_path(current_user.company), :class => "icon-edit icon-white edit-link pull-right company", :remote => true %>
    
  <% else %>
    <% if display_new_meeting_request_link_for?(@company) %>
      <%= link_to t('.meeting'), new_company_meeting_request_path(@company), class: 'pull-right meeting-link' %>
    <% end %>
  <% end %>
    
</div>

<div class="edit_company_box"></div>

app/views/companies/edit.html.erb
<%= content_for :header do %>
  <%= render partial: "companies/summary" %>
<% end %>

<%= render 'form' %>

app/views/companies/edit.js.erb
$('.edit_company_box').html('<%= escape_javascript render("form") %>');

app/views/companies/index.html.erb
<%= content_for :header do %>
  <%= render partial: "companies/summary" %>
<% end %>

<div class="row">
  <div class="span12">
    <div class="search-companies">
      <form class="form-search">
        <label for="company_name"><%=t '.search_company' %></label>
        <input type="text" id="company_name" name="company_name" value="<%= params[:company_name] %>" class="input-medium search-query">
        <button type="submit" class="btn"><i class="icon-search"></i></button>
      </form>
      <h3 class="section-title sector">
        <span class="sector-title"><%=t '.title' %></span>
        <div class="navbar">
          <div class="navbar-inner">
              <div class="container">
                <div class="nav-collapse collapse navbar-responsive-collapse">
                  <ul class="nav">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <% if !params[:sector_id] %>
                          <%=t '.all' %>
                        <% else %>
                          <%= @sector.name %>
                        <% end %>
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to t('.all'), companies_path %></li>
                        <% @sectors.each do |sector| %>
                          <li><%= link_to sector.name, companies_path(:sector_id => sector.id) %></li>
                        <% end %>
                      </ul>
                    </li>
                  </ul>                 
                </div><!-- /.nav-collapse -->
              </div>
            </div><!-- /navbar-inner -->
          </div>
      </h3>
      <table>
        <tbody>
          <% @companies.each do |company| %>
          <tr>
            <td class="company-logotype">
              <% if !company.logo.to_s.empty? %>
                <%= image_tag company.logo.to_s %>
              <% else %>
                <img src="http://placehold.it/100x100&amp;text=Company+Logo" />
              <% end %>
            </td>
            <td class="company-contact">
              <span class="name"><%= company.name.upcase %></span><br>
              <span class="contact-title"><%= Company.human_attribute_name :contact_person %></span>
              <span class="contact"><%= company.contact_person.full_name %></span>              
            </td>
            <td class="company-profile">
              <%= link_to company_path(company) do %>
                <%= image_tag("view-profile.png") %><br>
                <%=t '.profile' %>
              <% end %>
            </td>
            <td class="company-meeting">
              <% if display_new_meeting_request_link_for?(company) %>
                <%= link_to new_company_meeting_request_path(company) do %>
                  <%= image_tag("accept.png") %><br>
                  <%=t '.meeting' %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @companies %>
</div>
<br>

app/views/companies/show.html.erb
<%= content_for :header do %>
  <%= render partial: "companies/summary" %>
<% end %>

<div class="row">
  <div class="company">
    <h3 class="section-title info">
      <%= Company.human_attribute_name :summary %>
      <% if @company == current_user.company %>
        <a id="edit_company_summary" class="icon-edit icon-white edit-link pull-right info"> <%=t '.edit' %> </a>
      <% end %>
    </h3>
    <div id="summary-block" class="block">
      <span id="info_company_summary">
        <% if @company.summary.blank? && (@company == current_user.company) %>
          <%=t '.without_info' %>
        <% else %>
          <%= @company.summary %>
        <% end %>
      </span>
      <div class="company-summary">
        <%= form_for(@company) do |f| %>
          <%=f.text_area :summary, :rows => 5, :class => "span9", :value => @company.summary %>
          <%= f.submit "Actualizar datos", :class => "blue"%>
        <% end %>
      </div>
    </div>
  
    <h3 class="section-title services">
      <%= Company.human_attribute_name :services %>
      <% if @company == current_user.company %>
        <a id="edit_company_services" class="icon-edit icon-white edit-link pull-right info"> <%=t '.edit' %> </a>
      <% end %>
    </h3>
    <div id="services-block" class="block">
      <span id="info_company_services">
        <% if @company.services.blank? && (@company == current_user.company) %>
          <%=t '.without_info' %>
        <% else %>
          <%= @company.services %>
        <% end %>
      </span>
      <div class="company-services">
        <%= form_for(@company) do |f| %>
          <%=f.text_area :services, :rows => 5, :class => "span9", :value => @company.services %>
          <%= f.submit "Actualizar datos", :class => "green"%>
        <% end %>
      </div>
    </div>
  
    <h3 class="section-title needs">
      <%= Company.human_attribute_name :needs %>
      <% if @company == current_user.company %>
        <a id="edit_company_needs" class="icon-edit icon-white edit-link pull-right info"> <%=t '.edit' %> </a>
      <% end %>
    </h3>
    <div id="needs-block" class="block">
      <span id="info_company_needs">
        <% if @company.needs.blank? && (@company == current_user.company) %>
          <%=t '.without_info' %>
        <% else %>
          <%= @company.needs %>
        <% end %>
      </span>
      <div class="company-needs">
        <%= form_for(@company) do |f| %>
          <%=f.text_area :needs, :rows => 5, :class => "span9", :value => @company.needs %>
          <%= f.submit "Actualizar datos", :class => "orange"%>
        <% end %>
      </div>
    </div>
  
    <h3 class="section-title offers">
      <%= Company.human_attribute_name :offers %>
      <% if @company == current_user.company %>
        <a id="edit_company_offers" class="icon-edit icon-white edit-link pull-right info"> <%=t '.edit' %> </a>
      <% end %>
    </h3>
    <div id="offers-block"  class="block">
      <span id="info_company_offers">
        <% if @company.offers.blank? && (@company == current_user.company) %>
          <%=t '.without_info' %>
        <% else %>
          <%= @company.offers %>
        <% end %>
      </span>
      <div class="company-offers">
        <%= form_for(@company) do |f| %>
          <%=f.text_area :offers, :rows => 5, :class => "span9", :value => @company.offers %>
          <%= f.submit "Actualizar datos", :class => "dark-blue"%>
        <% end %>
      </div>
    </div>
  </div>
</div>