config/routes.rb
ContactoVeWebApp::Application.routes.draw do
  resources :surveys, :only => [:index, :edit, :update]

  resources :companies, :only => [:index, :show, :edit, :update] do
    resources :meeting_requests, only: [ :new, :create ]
  end

  resources :meetings, only: :index
  resources :meeting_requests, only: :index do
    member do
      get :accept
      get :reject
    end
  end

  devise_for :users

  namespace :admin do
    resources :users do
      collection do
        get :admins
        get :sponsors
        get :anchors
      end
    end

    resources :meetings
    resources :meeting_requests do
      member do
        get :notify
      end
    end
    resources :companies do
      collection do
        get :sponsors
        get :anchors
      end

      member do
        get :schedule
        get :send_schedule
      end
    end

    resources :surveys, :only => [:index, :edit, :update]

    get 'survey_users',     to: 'surveys#users'
    get 'survey_companies', to: 'surveys#companies'
    get 'survey_user/:id',  to: 'surveys#user', as: 'survey_user'

    authenticate :user, lambda { |u| u.admin? } do
      mount Resque::Server, :at => "/resque"
      mount MailPreview,    :at => "/mail_view"
    end
  end

  root 'dashboard#show'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
  has_many   :answers

  default_scope -> { order(:first_name) }
  scope :admins,   -> { where(admin: true) }
  scope :sponsors, -> { joins(:company).where(companies: { sponsor: true }) }
  scope :anchors,  -> { joins(:company).where(companies: { anchor: true }) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def to_s
    full_name
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdministrationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    def admins
      @users = User.admins
      render action: 'index'
    end

    def sponsors
      @users = User.sponsors
      render action: 'index'
    end

    def anchors
      @users = User.anchors
      render action: 'index'
    end

    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        else
          format.html { render action: 'new' }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        else
          format.html { render action: 'edit' }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        permitted_params = [:email, :first_name, :last_name, :phone_number, :company_id, :external_id]

        unless params[:user][:password].blank?
          permitted_params += [:password, :password_confirmation]
        end

        user_params = params.require(:user).send(:permit, permitted_params)
      end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [ :admin, @user ], :html => { :class => 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :company_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :company_id, Company.all, :id, :name, :class => 'text_field', include_blank: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :admin, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :admin, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mobile_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mobile_phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :external_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :external_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/users/index.html.erb
<%- content_for :header do -%>
<%= render partial: 'admin/menu' %>
<%- end -%>

<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<ul class="nav nav-pills">
  <li <%= 'class="active"'.html_safe if action_name == 'index' %>>
    <%= link_to t('.all'), admin_users_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'admins' %>>
    <%= link_to t('.admins'), admins_admin_users_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'sponsors' %>>
    <%= link_to t('.sponsors'), sponsors_admin_users_path %>
  </li>
  <li <%= 'class="active"'.html_safe if action_name == 'anchors' %>>
    <%= link_to t('.anchors'), anchors_admin_users_path %>
  </li>
</ul>

<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:external_id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:company_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.external_id %></td>
        <td>
          <%= user.full_name %>

          <% if user.mobile_phone %>
            <small>(<%= user.mobile_phone %>)</small>
          <% end %>

          <div class="email"><%= link_to user.email, admin_user_path(user) %></div>

          <% if user.admin %>
            <span class="badge badge-inverse">admin</span>
          <% end %>
          <% if user.company && user.company.sponsor %>
            <span class="badge badge-warning">sponsor</span>
          <% end %>
          <% if user.company && user.company.anchor %>
            <span class="badge badge-info">anchor</span>
          <% end %>
        </td>
        <td><%= user.company %></td>
        <td><%= user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      <tr>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_user_path,
            :class => 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
  <dd><%= @user.phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_id) %>:</strong></dt>
  <dd><%= link_to @user.company, [:admin, @user.company] if @user.company %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile_phone) %>:</strong></dt>
  <dd><%= @user.mobile_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:external_id) %>:</strong></dt>
  <dd><%= @user.external_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>